### ISSUE TITLE
Teleport to MHQ addaction missing

### ISSUE THREAD

**Issue by AtlasActual** [DarrellJMartin/ALiVE_Operation_Cobra.SPE_Normandy#2]
Reported on dedicated server that before respawning, the addaction to teleport to the mqh does not appear before the player respawns.

Tested on localhost addaction works wihtout respawning.

**Comment by AtlasActual** [comment]
So I just thought about this, it's most likely a JIP thing after the mhq has been deployed.

**Comment by DarrellJMartin** [comment]
Sorry, are you saying that the addaction to teleport to the mqh does not appear for JIP players IF the mhq is in a deployed state?

**Comment by AtlasActual** [comment]
> Sorry, are you saying that the addaction to teleport to the mqh does not appear for JIP players IF the mhq is in a deployed state?

That is correct

**Comment by DarrellJMartin** [comment]
Fixed
