### ISSUE TITLE
MHQ Deployment Clipping

### ISSUE THREAD

**Issue by AtlasActual** [DarrellJMartin/ALiVE_Operation_Cobra.SPE_Normandy#3]
Not sure how the script for deploying the mhq works, but from my experience sometimes the objects (flag pole, arsenal) will clip in objects and tumble. The arsenal crate then sets ablaze and creates smoke. 

Suggested fix: Have the objects deploy always to the 12 o'clock of the vehicle and put allowdamage false to the arsenal crate.

**Comment by DarrellJMartin** [comment]
Set allowdamage false to spawned MHQ assets
